# -*- coding: utf-8 -*-
"""
Created on Wed Mar 27 13:03:56 2024

@author: spuhlk01
"""

#USEFUL VARIABLES TO IMPORT FOR A WIDE RANGE OF SCRIPTS
#DO NOT EDIT WITHOUT DISCUSSING WITH KARL 


#MACHINE AND RV STUFF
TRUEBEAMS = ['TrueBeamSN1106']
EX = ['21EX']

VARIAN_MACHINES = TRUEBEAMS + EX


CYBERKNIFES    = ["C0480", "C0363"] 
CYBERKNIFE_NYC = ["C0363"]
CYBERKNIFE_LI  = [x for x in CYBERKNIFES if x not in CYBERKNIFE_NYC]

RADIXACTS = ['4010100_1000MU']

ACCURAY_MACHINES = CYBERKNIFES + RADIXACTS

ALL_MACHINES = VARIAN_MACHINES + ACCURAY_MACHINES


RS_UTIL_ARIA_CONNECTION           =  {'Node': '10.185.196.46', 'Port': 51408, 'CalledAE': 'VMSFSDRAYSTATION', 'CallingAE' : 'RAYSTATION_SSCP' }
RS_UTIL_PRECISION_CONNECTION_LI   =  {'Node': '10.22.228.17', 'Port': 11112, 'CalledAE': 'N1000_DICOMPLAN', 'CallingAE': 'RAYSTATION_SSCP'}
RS_UTIL_PRECISION_CONNECTION_NYC  =  {'Node': '10.22.189.5',  'Port': 11112, 'CalledAE': 'N1000_DICOMPLAN', 'CallingAE' : 'RAYSTATION_SSCP'}


OPT_STRUCTURE_COLOR = "#e32be3"